version: '3.4'

services:
  database:
    image: bitnami/mariadb:10.3.34
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: local
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "33306:3306"
    volumes:
      - "database:/bitnami/mariadb:rw"

volumes:
  database:
